version: '3.3'
services:
    backend_database:
      build: Backend/MySQL
      container_name: 'meteostaniceDatabaze'
      environment:
        MYSQL_DATABASE: 'meteoData'
        # So you don't have to use root, but you can if you like
        MYSQL_USER: 'root'
        # Password for root access
        MYSQL_ROOT_PASSWORD: 'Aa123456'
      ports:
        # <Port exposed> : < MySQL Port running inside container>
        - 3306:3306
      expose:
        # Opens port 3306 on the container
        - '3306'
      networks: 
        - sit
      volumes:
        - sqlData:/home/akr1j/Plocha/Maturita/
      restart: always

    web_grafana:
      #build: Grafana/
      image: grafana/grafana
      container_name: meteostaniceGrafana
      ports: 
        - 3000:3000
      expose: 
        - '3000'
      networks: 
        - sit
      volumes:
        - grafanaData:/home/akr1j/Plocha/Maturita/
      restart: always

    backend_node:
      #image: "node-docker"
      build: Backend/Node/
      #image: "node:8"
      container_name: meteostaniceNode
      #environment:
      #  - NODE_ENV=production
      #volumes:
      #  - ./:/home/node/app
      ports: 
        - 8888:8888
      expose:
        - '8888'
      networks:
        - sit
      
      #restart: always


      depends_on:
        - backend_database
      environment:
        - WAIT_HOSTS=backend_database:3306
        - WAIT_HOSTS_TIMEOUT=300
        - WAIT_SLEEP_INTERVAL=5
        - WAIT_HOST_CONNECT_TIMEOUT=30

networks:
  sit:
    driver: bridge

volumes: 
  sqlData:
  grafanaData: