{
 "title": "Venku",
 "time": { "from": "2020-10-23T19:00:00.000Z", "to": "2020-10-24T19:00:00.000Z" },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  TeplotaCas AS \"time\",\n  TeplotaTeplota AS \"Teplota\",\n  TeplotaVlhkost AS \"Vlhkost\",\n  TeplotaTlak AS \"Tlak\",\n  TeplotaCO2 AS \"CO2\"\nFROM teplota\nORDER BY TeplotaCas"
    }
   ]
  },
  {
   "title": "Teplota",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  TeplotaCas AS \"time\",\n  TeplotaTeplota AS \"Teplota\"\nFROM teplota\nORDER BY TeplotaCas"
    }
   ]
  },
  {
   "title": "Vlhkost",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  TeplotaCas AS \"time\",\n  TeplotaVlhkost AS \"Vlhkost\"\nFROM teplota\nORDER BY TeplotaCas"
    }
   ]
  },
  {
   "title": "Tlak",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  TeplotaCas AS \"time\",\n  TeplotaTlak AS \"Tlak\"\nFROM teplota\nORDER BY TeplotaCas"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  TeplotaCas AS \"time\",\n  TeplotaCO2 AS \"CO2\"\nFROM teplota\nORDER BY TeplotaCas"
    }
   ]
  }
 ]
}