# Dockerfile
FROM node:10

# wait for db
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.2.1/wait /wait
RUN chmod 777 /wait

RUN groupadd -r nodeuser \
   && useradd -m -r -g nodeuser nodeuser
USER nodeuser

RUN mkdir -p /home/nodeuser/app
WORKDIR /home/nodeuser/app

COPY package.json .
RUN npm install --production

COPY query.js ./src/query.js

CMD /wait && node src/query.js